@startuml

together {
    '接口的定义'
    interface Collection
    interface List
    interface Set
    interface Queue

    'abs 的定义'
    abstract class AbstractCollection
    abstract class AbstractList
        class ArrayList
        class Vector
            class Stack
    abstract class AbstractSequentialList
        class LinkedList
    abstract class AbstractSet
        class TreeSet
        class HashSet
            class LinkedHashSet
        abstract class EnumSet
            class JumboEnumSet
            class RegularEnumSet
        class CopyOnWriteArraySet
        class ConcurrentSkipListSet
    abstract class AbstractQueue
        class PriorityQueue
        class LinkedBlockingQueue
        class SynchronousQueue
        class ArrayBlockingQueue
        class DelayQueue
        class LinkedBlockingDeque
        class ConcurrentLinkedQueue

    '接口继承关系'
    Collection <|-- List
    Collection <|-- Set
    Collection <|-- Queue

    '接口实现关系'
    Collection <|.. AbstractCollection
    Iterable <|.. Collection
    List <|.. AbstractList
    Set <|.. AbstractSet
    Queue <|.. AbstractQueue

    'List'
    AbstractCollection <|-- AbstractList
    AbstractList <|-- AbstractSequentialList
        AbstractSequentialList <|-- LinkedList
    AbstractList <|-- ArrayList
    AbstractList <|-- Vector
            note right of Vector
            废弃
            end note
        Vector <|-- Stack
            note left of Stack
            废弃
            end note

    'Set'
    AbstractCollection <|-- AbstractSet
    AbstractSet <|-- TreeSet
    AbstractSet <|-- HashSet
        HashSet <|-- LinkedHashSet
    AbstractSet <|-- EnumSet
        EnumSet <|-- JumboEnumSet
        EnumSet <|-- RegularEnumSet
    AbstractSet <|-- CopyOnWriteArraySet
    AbstractSet <|-- ConcurrentSkipListSet

    'Queue'
    AbstractCollection <|-- AbstractQueue
    AbstractQueue <|-- SynchronousQueue
    AbstractQueue <|-- PriorityQueue
    AbstractQueue <|-- LinkedBlockingQueue
    AbstractQueue <|-- PriorityBlockingQueue
    AbstractQueue <|-- ArrayBlockingQueue
    AbstractQueue <|-- DelayQueue
    AbstractQueue <|-- LinkedBlockingDeque
    AbstractQueue <|-- ConcurrentLinkedQueue
}

together {
    interface Map
    abstract class AbstractMap
        class HashMap
        class WeakHashMap
        class IdentityHashMap
        class EnumMap
        class ConcurrentHashMap
        class ConcurrentSkipListMap
        class TreeMap

    Map <|.. AbstractMap

    AbstractMap <|-- HashMap
    AbstractMap <|-- WeakHashMap
    AbstractMap <|-- IdentityHashMap
    AbstractMap <|-- EnumMap
    AbstractMap <|-- ConcurrentHashMap
    AbstractMap <|-- ConcurrentSkipListMap
    AbstractMap <|-- TreeMap
}

@enduml